### ISSUE TITLE
dzsave with google layout ignores overlap setting

### ISSUE THREAD

**Issue by robclouth** [jcupitt/libvips#326] opened 2015-09-09 11:35 UTC
Hi,
It seems that whatever overlap value I put for the google layout, it's always 0. I looked at the source and it defaults to 0 for the google layout, but I can't override it.. I'm using the dev 8.0.2 prebuilt binaries.

Thanks

**Comment by jcupitt** [comment] 2015-09-09 12:01
Oh yes, how strange, I see this too. I'll have a look. Thanks the report.

**Comment by robclouth** [comment] 2015-09-09 12:07
It seems like it offsets the contents of the tile but doesn't increase the size of it to accommodate the overlap on the other side.

**Comment by jcupitt** [comment] 2015-09-09 16:32
It seems to work now, with your example anyway. I'll add some more tests to the test suite to pick up any future regressions and test a few other common cases.

It's in this branch:

https://github.com/jcupitt/libvips/compare/fix-dzsave-overlap

I was able to simplify the overlap handling a bit as well.

**Comment by robclouth** [comment] 2015-09-10 07:21
Great! Thanks. I'll test it out.

**Comment by robclouth** [comment] 2015-09-10 07:27
Actually no I won't because it's hell to build this on Windows. I'd forgotten. Any ideas when this might make it into the dev binaries?

**Comment by jcupitt** [comment] 2015-09-10 07:39
I'll make a test Windows build. Let me just try a few more of the obvious cases first. 

libvips 8.1 is due out in September, so this will be in that release at least.

**Comment by jcupitt** [comment] 2015-09-10 13:31
I've added some tests, which it seems to pass, and made a test Windows build:

http://www.vips.ecs.soton.ac.uk/development/

I've merged the new code into git master since it seems to be working. Any testing would be great!

**Comment by robclouth** [comment] 2015-09-10 15:26
Somethings are a bit weird. It doesn't quite work in my zooming software. The different levels are shifted by a small amount each time. Also, with the other layouts, overlap seems to be the double the entered value, e.g. '--overlap 2' makes an overlap of 4 pixels on each side. With the google layout '--overlap 2' makes an overlap of 2 pixels on each side. Is this expected behaviour? Something to do with the requirements of each layout format? Thanks

**Comment by robclouth** [comment] 2015-09-10 15:29
Here's what I was using:
vips dzsave ep_ssm.jpg ep_ssm --layout google --tile-size 197 --overlap 2 --depth onetile --background 0. 0.

**Comment by jcupitt** [comment] 2015-09-10 16:26
Hmm it seems to work for me, I tried:

```
$ vips dzsave k2.jpg ep_ssm --layout google --tile-size 197 --overlap 2 --depth onetile --background=0 --suffix .png
```

Then looked at the tiles in nip2:

```
$ nip2 k2.jpg ep_ssm/4/0/0.png ep_ssm/4/0/1.png ep_ssm/4/0/2.png
```

Looking at the image, those first three tiles are 197x197 and positioned at 0, 195 and 390. Is that correct? So each tile has a two pixel border where it overlaps with its neighbours.

**Comment by robclouth** [comment] 2015-09-10 21:19
Yeah I checked the output in photoshop for a single level and it works great. The problem I'm having is that in my zooming software, every time a new level is loaded it's slightly offset from the level below. The levels don't quite line up. Are you seeing this? This doesn't happen if I use the dz layout.

**Comment by jcupitt** [comment] 2015-09-11 12:19
It could be rounding differently on shrink I guess. 

Do you have a small working google maps pyramid (plus the original image, of course) you could send me? I'll see how they handle rounding.

**Comment by robclouth** [comment] 2015-09-11 13:40
Sure, where to?

**Comment by jcupitt** [comment] 2015-09-11 13:50
I'm jcupitt@gmail.com, or maybe one of the file transfer services?

**Comment by jcupitt** [comment] 2015-10-06 13:11
Closing due to inactivity, please reopen if this is still a problem.

**Closed by jcupitt** 2015-10-06 13:11 UTC
Labels: bug, in development

**Comment by unusual-thoughts** [comment] 2016-09-04 19:38
Hi, I still have a similar issue with latest git on linux.
On this source image:
![crowd1](https://cloud.githubusercontent.com/assets/8385247/18233402/dee8443a-72e6-11e6-8519-1f45cea0be9f.jpg)
`vips dzsave crowd.png output --layout google --tile-size 256 --overlap 192` produces:
![all](https://cloud.githubusercontent.com/assets/8385247/18233397/d79d6692-72e6-11e6-8ebf-d24a3c275074.jpg)

As you can see, only the first row and column actually overlap with the second row/column.

While `vips dzsave crowd.png output --layout dz --tile-size 256 --overlap 192` produces:
![all3](https://cloud.githubusercontent.com/assets/8385247/18233413/1faf6908-72e7-11e6-938d-ca010058cd2f.jpeg)
Which looks fine to me (the non-border tiles are 640 pixels across = 256+192+192)

I was expecting the google layout tiles to still be 256x256, but with 3/4 overlap as well.
