### ISSUE TITLE
Python bindings on Windows - typelib missing?

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#500] opened 2016-08-14 10:15 UTC
Hi,

As commented in another issue I was looking into enabling Python bindings of libvips on a Windows station. Admittedly I'm not particularly proud of shaming vips by using it on Windows at all, but as fate would have it, it would be substantially beneficial to my project.

I've been attempting to enable the Python bindings for some time, however it keeps failing on one step or another, and now lastly, after I read your confirmation that bindings should be supported (#92), I retried by downloading the build at `http://www.vips.ecs.soton.ac.uk/supported/current/win32/` but in this build I can't even find the `.typelib`-file to install (tried both `web` and `all`). At this point I'm not sure if I have a ghost in my machine or if it is actually missing from the zip.

Ignoring that, using the method you described in your post under issue #92, am I right to assume that the following when enabling Vips bindings?
- `.typelib` goes into `PYTHON_PATH\Lib\site-packages\gnome\lib\girepository-1.0`
- `Vips.py` goes into `PYTHON_PATH\Lib\site-packages\gi\overrides`
- add `VIPS_PATH\bin` to PATH

Also, using the installer mentioned for introspection setup installs a `Vips.py` in overrides path by default. Is this normal?

Lastly I want to emphasise how happy I am with your framework, and I'm extremely thankful for all the work you've done and your outstanding support on my technical struggles to befriend libvips even further ;-)

Sincerely,
Jonas Ogaard

**Comment by jcupitt** [comment] 2016-08-14 10:20
Oh dear, hang on, I'll have a look.

**Comment by Jondeen** [comment] 2016-08-14 10:22
Update: I checked a prior version - 8.3.1 - and it seems to be included there (under `lib/gi-repository`).

**Comment by jcupitt** [comment] 2016-08-14 10:25
Yes, looks like the typelib has somehow been dropped by the new build script, sorry. I'll try to fix it.

**Comment by Jondeen** [comment] 2016-08-14 10:37
Upon doing the modifications with the 8.3.1-package as listed above I now get the following error during Vips import:
```python
>>> from gi.repository import Vips
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27_64\lib\site-packages\gi\importer.py", line 115, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "C:\Python27_64\lib\site-packages\gi\overrides\__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "C:\Python27_64\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27_64\lib\site-packages\gi\overrides\Vips.py", line 52, in <module>
    Vips.init(sys.argv[0])
GLib.Error: g-invoke-error-quark: Could not locate vips_init: 'libvips.so.42': The specified module could not be found. (1)```

Any ideas?

**Comment by jcupitt** [comment] 2016-08-14 10:43
Oh strange, you'd think gmodule would look for` xxx.dll`. You could try renaming the libvips dll as `libvips.so.42` and see if it finds it.

**Comment by Jondeen** [comment] 2016-08-14 10:52
Tried `libvips.dll`, `libvips.so.42.dll`, `libvips.so.42`, `libvips.42.dll` - neither of which worked :(

**Comment by Jondeen** [comment] 2016-08-14 10:59
UPDATE: It did find it upon renaming, but another series of errors popped up. Hang on.

**Comment by Jondeen** [comment] 2016-08-14 11:14
UPDATE: Here is the new error it fails on. In *addition* to having a traceback identical to the one for not finding the `.dll` at all, it also gives a popup saying: 
`The procedure entry point libintl_printf could not be located in the dynamic link library D:\Programs\vips-dev-web-8.3.1\bin\libexif-12.dll.` 
and then, after clicking OK I get another one: 
`The procedure entry point libintl_printf could not be located in the dynamic link library D:\Programs\vips-dev-web-8.3.1\bin\libvips.so.42.`

**Comment by jcupitt** [comment] 2016-08-14 13:30
I've found a problem with the packaging script, updating now.

The typelib is taken from a linux build, since I make the DLL in a cross-compiler, and you can't cross-compile the introspection stuff. Since it just lists the types that a DLL contains, I hoped the linux typelib would work with windows as well.

However, it looks like the typelib might have the name of the library file embedded in it:

```
$ grep libvips.so.42 Vips-8.0.typelib 
Binary file Vips-8.0.typelib matches
```

I'll see if I can find out more.

**Comment by jcupitt** [comment] 2016-08-14 14:28
I've put up new vips-dev zips including the typelib, thanks for pointing this out!

Sadly it seems the linux typelib will not work on Windows. This lists some of the problems:

https://github.com/Guacamayo/meta-gir 

It seems the simplest fix would be to build directly on Windows. Failing that, we need something like meta-gir to run parts of the build system in qemu.

**Comment by Jondeen** [comment] 2016-08-15 06:04
OK, I'm just glad to learn it's not just me ;-)

Let me know if there is anything I can do to help, although these kind build environments leave me quite confused to be frank. Would you be using MingW for local compilation on Windows?

**Comment by jcupitt** [comment] 2016-08-15 11:05
Yes, it should compile easily with mingw/msys. Are there any free mingw/msys build services we could use? I've not looked.

**Comment by Jondeen** [comment] 2016-08-15 13:31
Looking into it. Is there any reason why configure.ac has DOS-type line endings? Had to run the following to have the git checkout compile:
```bash
mv configure.ac configure.ac.dos
tr -d '\015' <configure.ac.dos> configure.ac
```

**Comment by jcupitt** [comment] 2016-08-15 14:28
git master configure.ac is Unix-style:

```
$ od -xa configure.ac
0000000    2023    7250    636f    7365    2073    6874    7369    6620
          #  sp   P   r   o   c   e   s   s  sp   t   h   i   s  sp   f
0000020    6c69    2065    6977    6874    6120    7475    636f    6e6f
          i   l   e  sp   w   i   t   h  sp   a   u   t   o   c   o   n
0000040    2066    6f74    7020    6f72    7564    6563    6120    6320
          f  sp   t   o  sp   p   r   o   d   u   c   e  sp   a  sp   c
0000060    6e6f    6966    7567    6572    7320    7263    7069    2e74
          o   n   f   i   g   u   r   e  sp   s   c   r   i   p   t   .
0000100    0a0a    2023    6c61    6f73    7520    6470    7461    2065
         nl  nl   #  sp   a   l   s   o  sp   u   p   d   a   t   e  sp
```

There are two `nl` chars for the blank line.

**Comment by jcupitt** [comment] 2016-08-15 16:52
Also, I hope I didn't waste too much of your time :( I honestly though it was working. It's good to have a clearer idea of the current issues at least.

**Comment by Jondeen** [comment] 2016-08-15 19:17
Regarding DOS-style line endings; seems to be some funk my msys-environment is jazzing up. Tried on a fresh git clone again and this is what I get:
```bash
$ ./autogen.sh
testing for glibtoolize ... using libtoolize
' is already registered with AC_CONFIG_FILES.
../../lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:993: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal-1.15: error: echo failed with exit status: 1
' is already registered with AC_CONFIG_FILES.
../../lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:993: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
' is already registered with AC_CONFIG_FILES.
../../lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:993: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
autoheader: '/usr/bin/autom4te' failed with exit status: 1
' is already registered with AC_CONFIG_FILES.
../../lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:993: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
gautomake-1.15: error: autoconf failed with exit status: 1
```

**Comment by Jondeen** [comment] 2016-08-15 19:18
Now compiling, but g-ir-scanner whines about missing glib.h and glibconfig.h.

**Comment by Jondeen** [comment] 2016-08-15 20:19
Something for the folks at MSYS or do you have any idea of how to resolve this?
```bash
CPPFLAGS="" CFLAGS="-g -O2" LDFLAGS="" CC="x86_64-w64-mingw32-gcc"  /mingw64/bin/g-ir-scanner  --add-include-path=/mingw64/include/glib-2.0 --add-include-path=/mingw64/lib/glib-2.0/include --add-include-path=. --namespace=Vips --nsversion=8.0 --libtool="/bin/sh ../libtool"  --include=GObject-2.0   --library=libvips.la --program=./introspect --identifier-prefix=Vips --identifier-prefix=vips --symbol-prefix=vips  --cflags-begin  -I../libvips/include --cflags-end  --argfile=Vips-8.0.gir.files --output Vips-8.0.gir
In file included from c:/users/jonas/appdata/local/temp/g-ir-cpp-t3seqv.c:5:0:
C:/msys64/home/Jonas/libvips/libvips/include/vips/vips.h:85:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 536, in scanner_main
    ss = create_source_scanner(options, args)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 443, in create_source_scanner
    ss.parse_files(filenames)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/sourcescanner.py", line 305, in _parse
    self._cpp_options)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/ccompiler.py", line 199, in preprocess
    extra_postargs=extra_postargs)
  File "C:/msys64/mingw64/lib/python2.7/distutils/unixccompiler.py", line 111, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'C:\\msys64\\mingw64\\bin/x86_64-w64-mingw32-gcc.exe' failed with exit status 1
make[3]: *** [/mingw64/share/gobject-introspection-1.0/Makefile.introspection:174: Vips-8.0.gir] Error 1
make[3]: Leaving directory '/home/Jonas/libvips/libvips'
make[2]: *** [Makefile:847: all-recursive] Error 1
make[2]: Leaving directory '/home/Jonas/libvips/libvips'
make[1]: *** [Makefile:630: all-recursive] Error 1
make[1]: Leaving directory '/home/Jonas/libvips'
make: *** [Makefile:535: all] Error 2
``

**Comment by Jondeen** [comment] 2016-08-15 20:34
Ì forgot to mention I've tried both including the correct paths for glib through CPPFLAGS in Makefile and through --add-include-path argument of g-ir-scanner. Adding path to glib.h in CPPFLAGS resolves initial error but raises another when parsing  another header file in the glib includes:
```bash
CPPFLAGS="-I/mingw64/include/glib-2.0" CFLAGS="-g -O2" LDFLAGS="" CC="x86_64-w64-mingw32-gcc"  /mingw64/bin/g-ir-scanner  --add-include-path=/mingw64/include/glib-2.0 --add-include-path=/mingw64/lib/glib-2.0/include --add-include-path=. --namespace=Vips --nsversion=8.0 --libtool="/bin/sh ../libtool"  --include=GObject-2.0   --library=libvips.la --program=./introspect --identifier-prefix=Vips --identifier-prefix=vips --symbol-prefix=vips  --cflags-begin  -I../libvips/include --cflags-end  --argfile=Vips-8.0.gir.files --output Vips-8.0.gir
In file included from C:/msys64/mingw64/include/glib-2.0/glib/galloca.h:32:0,
                 from C:/msys64/mingw64/include/glib-2.0/glib.h:30,
                 from C:/msys64/home/Jonas/libvips/libvips/include/vips/vips.h:85,
                 from c:/users/jonas/appdata/local/temp/g-ir-cpp-ag7tet.c:5:
C:/msys64/mingw64/include/glib-2.0/glib/gtypes.h:32:24: fatal error: glibconfig.h: No such file or directory
 #include <glibconfig.h>
                        ^
compilation terminated.
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 536, in scanner_main
    ss = create_source_scanner(options, args)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 443, in create_source_scanner
    ss.parse_files(filenames)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/sourcescanner.py", line 305, in _parse
    self._cpp_options)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/ccompiler.py", line 199, in preprocess
    extra_postargs=extra_postargs)
  File "C:/msys64/mingw64/lib/python2.7/distutils/unixccompiler.py", line 111, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'C:\\msys64\\mingw64\\bin/x86_64-w64-mingw32-gcc.exe' failed with exit status 1
make[1]: *** [/mingw64/share/gobject-introspection-1.0/Makefile.introspection:174: Vips-8.0.gir] Error 1
make[1]: Leaving directory '/home/Jonas/libvips/libvips'
make: *** [Makefile:847: all-recursive] Error 1
```

**Comment by bgilbert** [comment] 2016-08-16 00:20
Depending on how it's configured, Git [may convert line endings during checkout](https://help.github.com/articles/dealing-with-line-endings/).  This can be prevented by committing a `.gitattributes` file; [here's the one we use in OpenSlide](https://github.com/openslide/openslide/blob/master/.gitattributes).

**Comment by jcupitt** [comment] 2016-08-16 08:23
I didn't know git did that, oh dear. Thank you @bgilbert.

**Comment by jcupitt** [comment] 2016-08-16 09:02
@Jondeen thank you for working on this. 

My guess would be you need another `-I`. glib splits the headers into architecture-neutral files, which go into `/usr/include/glib-2.0` on *nix, and an architecture-dependent headers (the value of various constants are for an exact machine), which go into `/usr/lib/xxxx/include/glib-2.0`. On my laptop, that's `/usr/lib/x86_64-linux-gnu/glib-2.0/include`.

It should do this automatically, I think, I'm unsure why msys has dropped this.

**Comment by Jondeen** [comment] 2016-08-16 12:29
Those are the locations of glib.h and glibconfig.h respectively, which are both included (base path is /mingw64). I'll see if I can get some know how from the MSYS community.

**Comment by Jondeen** [comment] 2016-08-16 12:35
@line endings, this only raises an issue on my msys/mingw checkout. And I'm not sure if it's only one line that's the issue or if it is the whole file - it raises the error for line 993 so probably it got that far without any line ending magic. All I know is that vim recognises it as a DOS-type line ending file and performing the tr-trick works :-)

**Comment by jcupitt** [comment] 2016-08-16 12:56
There are no line breaks in git master here, something else must be happening. No idea what though! Perhaps one of the other tools that processes the file is adding a DOS line break?

```
$ tr -d '\015' <configure.ac >x
$ ls -l x configure.ac
-rw-rw-r-- 1 john john 33337 Aug 16 13:48 configure.ac
-rw-rw-r-- 1 john john 33337 Aug 16 13:49 x
```

**Comment by Jondeen** [comment] 2016-08-16 13:10
```
$ git clone https://github.com/jcupitt/libvips.git
Cloning into 'libvips'...
$ tr -d '\015' <configure.ac >x
$ ls -l configure.ac x
-rw-r--r-- 1 Jonas Jonas 32874 Aug 16 15:06 configure.ac
-rw-r--r-- 1 Jonas Jonas 32874 Aug 16 15:06 x
$ ./autogen.sh
testing for glibtoolize ... using libtoolize
configure.ac:246: installing './compile'
configure.ac:125: installing './config.guess'
configure.ac:125: installing './config.sub'
configure.ac:13: installing './install-sh'
configure.ac:13: installing './missing'
cplusplus/Makefile.am: installing './depcomp'
python/packages/gi/overrides/Makefile.am:2: installing './py-compile'
parallel-tests: installing './test-driver'
```

Now it works :D

**Comment by Jondeen** [comment] 2016-08-16 13:14
This was probably because it used windows git to pull the files. I just found git binaries path in $PATH (which pulls in everything from windows PATH variable).

**Comment by jcupitt** [comment] 2016-08-16 13:14
Heh oh well, I'm glad that's working at least. I committed a `.gitattributes`, following Benjamin's advice, perhaps that did it.

**Comment by Jondeen** [comment] 2016-08-16 13:46
Ref: https://sourceforge.net/p/msys2/tickets/278/

**Comment by jcupitt** [comment] 2016-08-25 13:30
I've been thinking about this some more. 

typelibs are not portable between linux and Windows because they include details of very low level things like struct layout, which will vary between compilers and certainly between linux and win. But I don't think the python binding for vips accesses any struct members, I think it sticks to simple function calls, plus GValues for parameter types. So there's a good chance the linux typelib, though not strictly correct, will just work. 

The way to test this would be to try running the vips testsuite on Windows. It's all in python and it's fairly complete, so if it gets through that, we should be A-OK. The code is here:

https://github.com/jcupitt/libvips/blob/master/test/test_all.py

On linux you can run it like this:

```
$ ./test_all.py 
...............................................................................................................................................................................
----------------------------------------------------------------------
Ran 175 tests in 48.007s

OK
```

So I would suggest an experiment:

* download the latest win64 vips binary (it includes the linux typelib)
* install a 64-bit python
* install one of the pygobject all-in-one packages, there seem to be a few floating about
* verify that you can run a gtk+ "hello world!" program in your 64-bit python ... make sure it's gtk+3 and using the GOI binding, not the old gtk+2 static binding
* copy the vips DLLs, typelib and Vips.py to the appropriate places in the all-in-one
* see if you can run a vips "hello world"
* see if you can run the vips test suite

A vips `hello-world.py` might be:

```python
# for this to work, the typelib and DLLs have to be findable
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

# this will only work if the VIps.py overrides file has been found
pixel = Vips.Image.black(1, 1)
```

**Comment by strets123** [comment] 2016-08-25 15:10
Thanks for looking into this John, hopefully I will get a chance to  try out your suggestions in the next couple of months. Currently we are using Pillow on Windows which is quite a lot slower than Vips.

**Comment by Jondeen** [comment] 2016-09-25 11:16
Hi, and my apologies for not getting back to you sooner...

I tried the process as described by @jcupitt on August 25th, however to no avail. GTK runs fine, but then it starts complaining about `"The procedure entry point libintl_printf could not be located in the dynamic link library [VIPS-path]\bin\libexif-12.dll"`.

**Comment by tumagonx** [comment] 2017-05-11 12:54
Hi If you interested I maintain Gobject-related libraries collection a long while ago (including VIPS) https://sourceforge.net/projects/pygobjectwin32/files/?source=navbar

**Comment by tumagonx** [comment] 2017-05-11 12:58
the patch for VIps to generate binding properly is here https://github.com/tumagonx/pygi-mingw-patches/blob/master/vips-8.4.x.patch

But i don't know if it will harm linux? I'm no linux user.
BTW the build is fairly complete in LGPL-like (avoiding FFTW)

**Comment by strets123** [comment] 2017-05-11 13:13
Thanks, in the end we were able to gain higher performance and a lot less hassle/dependencies than libvips cross-platform by using https://github.com/uploadcare/pillow-simd

**Comment by tumagonx** [comment] 2017-05-11 13:17
Understood.. pillow should be more pythonic :)

**Comment by jcupitt** [comment] 2017-05-11 13:26
I like your patch @tumagonx, I'll see if I can add it to master. 

I'd not heard of pillow-simd, that's interesting, I'll have a look.

**Comment by jcupitt** [comment] 2017-05-13 13:08
I've incorporated @tumagonx's patches into master libvips, perhaps things will be simpler in future. 

I tried pillow-simd on the vips benchmark: vips using lanczos was about 20% faster single-threaded, or ~5x faster on that large 6-core machine.

**Comment by strets123** [comment] 2017-05-13 18:34
@jcupitt thanks for the benchmark, the issue must be in my implementation.

**Comment by kleisauke** [comment] 2017-07-27 11:32
I could reproduce these 2 errors:
```
The procedure entry point libintl_printf could not be located in the dynamic link library C:\vips-8.5.6\bin\libexif-12.dll.
The procedure entry point libintl_printf could not be located in the dynamic link library C:\vips-8.5.6\bin\libvips-42.dll.
```

Steps to reproduce these errors:
- Install Python 3 (with Pacman which ships in MSYS2):
   ```bash
   pacman -S mingw-w64-x86_64-python3
   ```
- Try to import the `libvips-42.dll`
   ```bash
   python3 -c "from ctypes import cdll; cdll.LoadLibrary(\"C:\\vips-8.5.6\\bin\\libvips-42.dll\")"
   ```
   
The underlying problem is that `libintl-8.dll` is getting included from the MinGW-w64 bin directory (`C:\msys64\mingw64\bin`) instead than from the libvips bin directory (in my case `C:\vips-8.5.6\bin`).

When opening `libintl 0.19.8.1` (from `C:\msys64\mingw64\bin`) in Dependency Walker, I see there's no `libintl_printf`:
![no_printf_ruby](https://user-images.githubusercontent.com/12746591/28662636-1da30a28-72bb-11e7-8b50-0d94bccbf878.png)

There's a `libintl_printf` in the `libintl 0.18.1` (included by `libexif 0.6.21` from `C:\vips-8.5.6\bin`): 
![printf_libvips](https://user-images.githubusercontent.com/12746591/28662634-1b23bf90-72bb-11e7-8a9d-c5f2afcbc441.png)

A simple fix is renaming `C:\msys64\mingw64\bin\libintl-8.dll` to `C:\msys64\mingw64\bin\libintl-8.dll.old` or replacing it by the `libintl-8.dll` from `C:\vips-8.5.6\bin`. 

But this feels hackish, I tried to change the load-order for DDLs by placing the `C:\vips-8.5.6\bin` path above `C:\msys64\mingw64\bin` in the `PATH` environment variable but this doesn't make any difference.

If someone knows a better fix, let me hear! :smile:

**Comment by tumagonx** [comment] 2017-07-27 21:50
maybe re-order your %PATH% enviroment?

**Comment by jcupitt** [comment] 2017-07-28 10:57
This really is a huge pain, thank you very much for working on this, Kleis.

I think part of the problem is the huge and wobbly stack the Python binding is built upon. It does work, but installation, testing and porting is more difficult than it should be.

We've just reworked the Ruby binding to sit on top of FFI and GObject rather than on top of gobject-introspection. The API is the same for users of `ruby-vips`, but the stack is a lot smaller and simpler to maintain. It's been a good experience!

https://github.com/jcupitt/ruby-vips/tree/ffi-experiment

Perhaps we could do the same for the Python binding? I'd guess it would be about a week's work. If it became pure Python and only depended on CFFI, it'd work on CPython and PyPy, Windows would be much simpler, packaging for pip would be simple, and it should be a bit faster as well.

Would anyone be interested in collaborating?

**Comment by jcupitt** [comment] 2017-07-28 10:59
... and we could implement things like Buffer as well, and save copies when moving image in and out of pyvips as memory objects.

**Comment by jcupitt** [comment] 2017-07-30 10:49
Issue for a new Python binding: https://github.com/jcupitt/libvips/issues/699

**Comment by jcupitt** [comment] 2017-08-21 15:02
There's a new libvips binding for Python:

https://pypi.python.org/pypi/pyvips

This one uses cffi instead of gobject-introspection, so it's much, much simpler to install. All you need to do is get the libvips shared library on your system somehow, then `pip install pyvips` and that's it. 

The API is the same, you just need to put `import pyvips` at the top and everything should work. The docs are much better too:

https://jcupitt.github.io/pyvips

**Closed by jcupitt** 2017-08-21 15:03 UTC
Labels: question
