### ISSUE TITLE
Resize seems to be off center when scaling up

### ISSUE THREAD

**Issue by tback** [jcupitt/libvips#705] opened 2017-08-04 12:32 UTC
When upscaling images it libvips underrepresents pixels from the top and the left border of an image.

I noticed this as a user of https://github.com/h2non/bimg but could easily reproduce it on the vips cli. I created a tiny image (20x30 pixels) and blew it up by a factor of 8:

This is the base image:
![small](https://user-images.githubusercontent.com/83432/28968390-0497b84c-7920-11e7-96e4-fddfa3193479.jpg)

I installed vips via `brew install vips` on macos 10.12.4 (16E195). The version I use is the latest available today on homebrew: 

```
/usr/local/opt/vips/bin/vips -v
vips-8.5.7-Fri Aug  4 13:47:32 CEST 2017
```

Now I created the left image below using vips (`/usr/local/opt/vips/bin/vips resize img/small.jpg f8-vips.jpg 8`). I created the right image using gimp to illustrate what the result is supposed to look like - it is immediately obvious that pixels from the top and the left are underrepresented in what looks like a classical off by one error:

![f8-vips](https://user-images.githubusercontent.com/83432/28968389-0494ee3c-7920-11e7-96fc-01e5c6ce4ac4.jpg) ![f8-gimp](https://user-images.githubusercontent.com/83432/28968391-04ac548c-7920-11e7-9b53-c22ecdaf2902.jpg)

**Comment by kleisauke** [comment] 2017-08-04 13:34
(I'm not the author of libvips)

It's better to use the nearest-neighbor interpolation for pixel art, in libvips this can be set using the `--kernel` option, see:
```bash
vips resize small.jpg small-resize-nearest.jpg 8 --centre --kernel nearest
```
![small-resize-nearest](https://user-images.githubusercontent.com/12746591/28970142-bbf37380-7927-11e7-9436-8cf5bb1ac91c.jpg)

Or for a fast, integral nearest-neighbor enlargement, you could use the `zoom` operation:
```bash
vips zoom small.jpg small-zoom.jpg 8 8
```
_(same output as above)_

Returning to the issue, it looks like a bug. Even with the `--centre --kernel cubic` option I reproduce the same output as yours (GIMP is using the cubic interpolation as default).

**Comment by tback** [comment] 2017-08-04 13:39
Built from git with DEBUG_VERBOSE in affine.c now. For some reason the the input image grows by three pixels at some point:
```
/Users/tback/vips/bin/vips resize img/small.jpg f8-vips.jpg 8
vips_affine_build: copy on identity transform disabled
vips_affine_build: transform: vips__transform_print:
 iarea: left=0, top=0, width=30, height=20
 oarea: left=0, top=0, width=240, height=160
 mat: a=8, b=0, c=0, d=8
 off: odx=0, ody=0, idx=0, idy=0
 window_offset = 1, window_size = 4
 input image width = 33, height = 23    <--- input image grew by three pixels in both dimensions
 output image width = 240, height = 160
vips_affine_gen: generating left=0, top=0, width=240, height=16
vips_affine_gen: preparing left=0, top=0, width=33, height=6
vips_affine_gen: generating left=0, top=16, width=240, height=16
vips_affine_gen: preparing left=0, top=1, width=33, height=7
vips_affine_gen: generating left=0, top=32, width=240, height=16
vips_affine_gen: preparing left=0, top=3, width=33, height=7
vips_affine_gen: generating left=0, top=48, width=240, height=16
vips_affine_gen: preparing left=0, top=5, width=33, height=7
vips_affine_gen: generating left=0, top=64, width=240, height=16
vips_affine_gen: preparing left=0, top=7, width=33, height=7
vips_affine_gen: generating left=0, top=80, width=240, height=16
vips_affine_gen: preparing left=0, top=9, width=33, height=7
vips_affine_gen: generating left=0, top=96, width=240, height=16
vips_affine_gen: preparing left=0, top=11, width=33, height=7
vips_affine_gen: generating left=0, top=112, width=240, height=16
vips_affine_gen: preparing left=0, top=13, width=33, height=7
vips_affine_gen: generating left=0, top=128, width=240, height=16
vips_affine_gen: preparing left=0, top=15, width=33, height=7
vips_affine_gen: generating left=0, top=144, width=240, height=16
vips_affine_gen: preparing left=0, top=17, width=33, height=6
memory: high-water mark 262.39 KB
```

**Comment by tback** [comment] 2017-08-04 13:50
Thanks for the tip about pixel art @kleisauke. This is not about pixel art though, it's just about reproducing the error in some way that makes it obvious to the naked eye.

Your example doesn't neglect the top left. It also doesn't grow the image by three pixels:
```
/Users/tback/vips/bin/vips resize small.jpg small-resize-nearest.jpg 8 --centre --kernel nearest
vips_affine_build: copy on identity transform disabled
vips_affine_build: transform: vips__transform_print:
 iarea: left=0, top=0, width=30, height=20
 oarea: left=0, top=0, width=240, height=160
 mat: a=8, b=0, c=0, d=8
 off: odx=0, ody=0, idx=0, idy=0
 window_offset = 0, window_size = 1
 input image width = 30, height = 20
 output image width = 240, height = 160
vips_affine_gen: generating left=0, top=0, width=240, height=16
vips_affine_gen: preparing left=0, top=0, width=30, height=3
vips_affine_gen: generating left=0, top=16, width=240, height=16
vips_affine_gen: preparing left=0, top=1, width=30, height=4
vips_affine_gen: generating left=0, top=32, width=240, height=16
vips_affine_gen: preparing left=0, top=3, width=30, height=4
vips_affine_gen: generating left=0, top=48, width=240, height=16
vips_affine_gen: preparing left=0, top=5, width=30, height=4
vips_affine_gen: generating left=0, top=64, width=240, height=16
vips_affine_gen: preparing left=0, top=7, width=30, height=4
vips_affine_gen: generating left=0, top=80, width=240, height=16
vips_affine_gen: preparing left=0, top=9, width=30, height=4
vips_affine_gen: generating left=0, top=96, width=240, height=16
vips_affine_gen: preparing left=0, top=11, width=30, height=4
vips_affine_gen: generating left=0, top=112, width=240, height=16
vips_affine_gen: preparing left=0, top=13, width=30, height=4
vips_affine_gen: generating left=0, top=128, width=240, height=16
vips_affine_gen: preparing left=0, top=15, width=30, height=4
vips_affine_gen: generating left=0, top=144, width=240, height=16
vips_affine_gen: preparing left=0, top=17, width=30, height=3
memory: high-water mark 258.34 KB
```

**Comment by jcupitt** [comment] 2017-11-25 12:07
Hello, sorry for the delay.

The shift is caused by centre vs. corner convention. libvips is corner convention, but gimp and imagemagick are centre.

 `resize` was applying the `--centre` flag to downsize, but (in an oversight) not to upsize. I've added the 0.5 pixel shift to git master and I now see:

![3x3](https://user-images.githubusercontent.com/580843/33230325-094d1a78-d1d9-11e7-8272-efc890482cbf.png)

![x](https://user-images.githubusercontent.com/580843/33230326-0ed387fc-d1d9-11e7-99c4-6d0dd7cebe82.png)

with:

```
$ vips resize 3x3.png x.png 10 --centre
```

which seems to match IM and gimp.

Thanks for spotting this! The fix is in 8.6.

**Comment by jcupitt** [comment] 2017-11-25 12:14
@tback the image grows because of the interpolator stencil. For cubic (the default upsize interpolator), you need a 4x4 block of input pixels for each output pixel. In order to be able to place the stencil at every point in the input, libvips adds a pixel along the top and left edges and two pixels along the bottom and right.

**Comment by jcupitt** [comment] 2017-11-25 14:03
Thinking about this some more, people usually recommend centre for upsize and corner for downsize. Let's deprecate the `centre` option and switch automatically. 

Resize is a compound operation: it doesn't do much itself, it just glues standard libvips operations together in a recommended way. It seems daft to have to use options to get it to do the right thing.

**Comment by jardakotesovec** [comment] 2017-11-26 14:58
@jcupitt I am wondering why you have chosen corner convention on downsizing if it results in slight image [shift](https://github.com/jcupitt/libvips/issues/504)?

**Comment by jcupitt** [comment] 2017-11-26 15:20
Yes, I've been worrying about this as well, I think it might have to go back. i have some other test images I need to try with.

**Comment by jcupitt** [comment] 2017-11-26 15:26
... I swapped it back, it's now always centre for downsize. Sorry for messing this up.

**Comment by tback** [comment] 2017-11-27 10:27
Checked it with 601396228884c94936a434eab47624bdaf33c87b, which looks good to me now.

**Comment by jcupitt** [comment] 2017-11-27 11:46
OK, I'll close. Thanks again!

**Closed by jcupitt** 2017-11-27 11:46 UTC
Labels: bug, in development
