### ISSUE TITLE
Second call to vips_init causes later program crash

### ISSUE THREAD

**Issue by DFKSingleton** [jcupitt/libvips#450] opened 2016-05-22 06:59 UTC
My problem is illustrated by the following small test program:

#include <stdio.h>
#include <vips/vips8>
#define RC_OK 0
using namespace vips;
int main(int argv, char ** argc) {
   printf("VipsRestartTest starting\n");
   for (int i = 0; i < 2; i++) {
      printf("   starting loop %d\n", i);
      int iRc = vips_init(argc[0]);
      if (RC_OK != iRc) {
         printf("unable to start VIPS\n");
      }
      // read a file
      VImage image =
            VImage::new_from_file(
                  "D:/Workarea/Cplusplus/VipsTest2/Testinput1/006E07875254_20160223041701.jpg");
      vips_shutdown();
   }
   printf("VipsRestartTest ending\n");
   return 0;
}

The program then crashes in the second call to new_from_file(). (The name of the .jpg file is irrelevant - one can use any .jpg file.)

I have debugged VIPS a bit and have found that the problem seems to be in vips_init(). Here there is a test `if (done) return 0;`
The effect of this is that that the second call to vips_init() does not carry out any initialisation and the program then crashes (segmentation fault) in new_from_file().

You may well ask why do i want to reinitialise VIPS during a program run. The reason for this is that I am using VIPS to process a series of pictures from a camera - and the program should run continuously. I have the problem that the memory usage climbs continuously (I use vips_tracked_get_mem() to report this.) valgrind and vips_leak_test() do not report any memory leaks when the program stops, so I want to implement a quick (and dirty?) fix to restart the VIPS subsystem when the memory usage is too big. I must of course find out why the memory usage increases, but that will take some time!

I am using vips 8.2.2 at the moment

Thanks in advance for a fix to the problem.

David Singleton

**Comment by jcupitt** [comment] 2016-05-22 08:55
Hi David,

vips doesn't support unload/reload. You can call `vips_init()` many times, but you can only call vips_shutdown() once, and once you've shut down, you can't start again. Perhaps I should add a note to the docs.

It shouldn't leak, and memory use should be stable. Can you make some test code which shows bad memory behaviour?

You might be seeing the vips operation cache. It keeps the last 1,000 or so operations in a cache just in case you repeat yourself. You could try turning this off. Add the line:

```
vips_cache_set_max(0);
```

After `vips_init()`.

John

**Comment by jcupitt** [comment] 2016-05-22 09:33
I made a test program:

https://gist.github.com/jcupitt/7c3c727dab644f394cea133bd9fbb79f

Watching RSS in `top`, I see a pretty steady 100MB memory use over the 2,000 image run, it wobbles up and down a bit, between about 95MB and 102MB, but it's reasonably stable. The vips leak thing reports a peak of 20MB.

If I remove the `vips_cache_set_max(0);` I see memory use in top climb to about 200MB and stabilize there. vips leak reports a peak of 100MB.

**Comment by DFKSingleton** [comment] 2016-05-22 17:57
Hello John,

Thanks very much for the quick reply. A pity, that `vips_shutdown()` can only be called once! That means that I cannot use my quick and dirty solution! My program reports regularly (every 10 input pictures) the cache and memory used (as reported by `vips_cache_get_size() and vips_tracked_get_mem ()`). As the tracked memory reaches 100Mb, the number of operations in the cache reduces to zero. As I was debugging, I noticed a comment in your code to this effect. 

I am now in the process of instrumenting my code, to try and localise the point where the tracked memory increases. When I have a better idea, I can write a test program to better identify the problem. This is likely to take some time. I will let you know when I have more information. 

Best wishes

David Singleton

**Comment by jcupitt** [comment] 2016-05-23 12:34
Hi again David, I added a note to the docs about this. Good luck tracking down your memory bloat issue.

I generally start with the smallest program that works and then copy-paste in features from the failing program until I see the problem. I don't know if that would be possible in your case.

**Comment by DFKSingleton** [comment] 2016-06-04 07:34
Hello John,

Thanks for your suggestion. I tried it, but unfortunately it did not help. 

I have a test set of some 9000 pictures that come from my camera. The first thing that I have noticed is that the cache and memory usage as reported by vips_cache_get_size() and vips_tracked_get_mem() (results written regularly to a text file throughout the run) are not consistent between runs, although the input data is identical. My first thought was that the inconsistency 
inconsistency could be due to VIPS multithreading, so I reduced the thread count to 1 with vips_concurrency_set(1). Despite this, I still get inconsistent cache and memory usage results between runs. 

I am working on reducing the number of input pictures, to see if I can find a smaller test set, but I have the impression that I am coming nowhere fast! As I write, I have had the idea that perhaps I should be looking for the reason for the cache and memory run inconsistencies rather than trying to find a smaller test set.

If all else fails, I will write a wrapper program that restarts my main program when the memory usage bloats too much. 

Do you have any suggestions where I could look further for the problem? Please do not be afraid to say "No"! There are only so many hours in a day!

Best wishes

David Singleton

**Comment by DFKSingleton** [comment] 2016-06-04 07:35
I did not mean to close the issue!

**Comment by jcupitt** [comment] 2016-06-04 08:49
Hi again, could you share your code? I could have a look if you like.

**Comment by jcupitt** [comment] 2016-06-04 09:15
I made a tiny program:

```python
#!/usr/bin/python

import sys
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

for name in sys.argv[1:]:
    print name, "cache =", Vips.cache_get_size(), "mem =", Vips.tracked_get_mem()
    image = Vips.Image.new_from_file(name, access = Vips.Access.SEQUENTIAL)
    image = image.resize(100.0 / image.width)
    image.write_to_file("tn_" + name)
```

If I make 10000 test images:

```
$ time for i in {1..10000}; do cp ~/pics/k2.jpg $i.jpg; done
real	0m29.631s
user	0m1.060s
sys	0m2.308s
```

`k2.jpg` is a 2048x1450 RGB jpg image. When I run it, I see:

```
$ time ../process.py *
10000.jpg cache = 0 mem = 0
1000.jpg cache = 17 mem = 677493
1001.jpg cache = 33 mem = 1354948
1002.jpg cache = 49 mem = 2032403
1003.jpg cache = 65 mem = 2709858
1004.jpg cache = 81 mem = 3387313
1005.jpg cache = 97 mem = 4064768
...
1162.jpg cache = 1000 mem = 103729113
1163.jpg cache = 1000 mem = 104165801
1164.jpg cache = 0 mem = 104602489
1165.jpg cache = 0 mem = 104687631
1166.jpg cache = 0 mem = 104864927
1167.jpg cache = 0 mem = 104991374
1168.jpg cache = 0 mem = 105038044
1169.jpg cache = 0 mem = 105080360
116.jpg cache = 0 mem = 105080360
1170.jpg cache = 0 mem = 105122676
1171.jpg cache = 0 mem = 105164973
1172.jpg cache = 0 mem = 105172473
1173.jpg cache = 0 mem = 105214789
1174.jpg cache = 0 mem = 105214789
....
9998.jpg cache = 0 mem = 105214789
9999.jpg cache = 0 mem = 105214789
999.jpg cache = 0 mem = 105214789
99.jpg cache = 0 mem = 105214789
9.jpg cache = 0 mem = 105214789
real	6m50.016s
user	6m19.244s
sys	0m17.384s
```

If I watch in `top`, RES seems stable at about 170MB.

I'm puzzled by the cache behaviour, I'd expect it to keep the most recent 1,000 operations, not drop ops to zero. I'll have a look.

**Comment by DFKSingleton** [comment] 2016-06-05 07:54
Hello John,

Thanks very much for the offer to look at my code. I just need to enhance the documentation in the code to make it easier to understand. That will take a day or two! I will then send you everything zipped together. I am sure that you will understand that I am not happy to post the complete code in an open forum. Is it OK if I send the zip file to your email address: jcupitt@imperial.ac.uk?

Best wishes

David Singleton

**Comment by jcupitt** [comment] 2016-06-05 08:51
Sure, or use my gmail address, it's less likely to be rejected.

**Comment by jcupitt** [comment] 2016-06-05 17:13
I found a problem with the operation cache: in some circumstances it will slowly fill with junk. I've added a thing to unjunk it and I now see:

```
$ time ../process.py *
10000.jpg cache = 0 mem = 0
1000.jpg cache = 17 mem = 677493
1001.jpg cache = 33 mem = 1354948
1002.jpg cache = 49 mem = 2032403
1003.jpg cache = 65 mem = 2709858
1004.jpg cache = 81 mem = 3387313
...
9997.jpg cache = 1000 mem = 42679609
9998.jpg cache = 1000 mem = 42679609
9999.jpg cache = 1000 mem = 42679609
999.jpg cache = 1000 mem = 42679609
99.jpg cache = 1000 mem = 42679609
9.jpg cache = 1000 mem = 42679609
real	6m37.164s
user	6m13.608s
sys	0m10.756s
```

So the cache stays at 1,000 operations, and memuse at 43mb, a 60mb saving.  

That shouldn't be the cause of your problems though. Send me a zip.

**Comment by DFKSingleton** [comment] 2016-06-05 20:10
Hello John,

I am afraid that I do not have your gmaIl address. (or at least I have overeen it in the VIPS documentation). Can you send it to me?

Thanks in advance.

David Singleton

**Comment by jcupitt** [comment] 2016-06-10 13:43
I found a couple more problems in vips :( `vips_image_write()` was holding a reference to its input when it didn't need always to, and the body for `VImage::write()` was missing. 

With these fixes (in git master, will be in 8.4), this program now runs in constant memory for any number of files:

```C++
/* compile with
 * 	g++ -g -Wall try236.cpp `pkg-config vips-cpp --cflags --libs`
 */

#include <stdio.h>
#include <stdlib.h>

#include <vips/vips8>

using namespace vips; 

int
main( int argc, char **argv )
{
	bool have_accumulator;
	VImage accumulator;

	if( VIPS_INIT( argv[0] ) )
		vips_error_exit( NULL );

	vips_cache_set_max( 0 ); 
	vips_leak_set( TRUE ); 

	have_accumulator = false;
	for( int i = 2; i < argc; i++ ) {
		printf( "image %d ...\r", i - 1 );
		fflush( stdout ); 

		//vips_object_print_all(); 

		VImage im = VImage::new_from_file( argv[i], 
			VImage::option()->set( "access", "sequential" ) ); 

		if( have_accumulator ) 
			im = im + accumulator;

		VImage memory = im.write( VImage::new_memory() ); 

		accumulator = memory;
		have_accumulator = true;
	}

	accumulator.write_to_file( argv[1] ); 

	printf( "\n" ); 

	return( 0 );
}
```

**Comment by DFKSingleton** [comment] 2016-06-14 11:26
Hello John,

Once more thanks for all the hep you have given me. I now want to report that I heve tested my program with the GIT master version of libvips. In two separate test scenarios of mine, it looks as if  issue "free non-worker buffers #466" has fixed my memory bloat problem. The memory usage rises to about 100MB and stays there. The cache usage does not go to zero any more! Super!

Best wishes and thanks for the super support! The issue can now be closed if you want.

David Singleton

**Comment by jcupitt** [comment] 2016-06-14 12:05
Great! I'm glad it's working now. And thanks for pushing on this issue, it's nice improvement.

**Closed by jcupitt** 2016-06-14 12:05 UTC
Labels: question
