### ISSUE TITLE
Force python calculation before writing to file

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#310] opened 2015-07-06 09:03 UTC
Hi,

In my infamous polygon-cutting script (updated here: https://gist.github.com/Jondeen/5a7043a7de7bf4cbdc4f#file-roicutterv2-py ) I attempt to cut down a big image to it's theoretical maximum size based on minimum and maximum values for the coordinates of the polygon, in advance of the polygon-coordinate testing.

Considering the lag I get on massive images here it seems as though the tests are all chained and performed on the full dataset(?) regardless of the `trim`-operation in the middle. Is there any way I can force the parser to recompile the image buffer after the trim operation?

Naturally, I may have misunderstood the structure and nature of the chained operations, but I see few other reasons why the large files should differ so much from the smaller ones -- any enlightenment is much appreciated!

**Comment by jcupitt** [comment] 2015-07-06 10:31
Ooop, sorry, I need to look at your masking script.

It's all on-demand, so it will only calculate the bits it needs for the final image. If you mask the whole file then crop out a bit of the mask and just write that, it'll only calculate that small part of the mask.

If you're seeing a long delay in startup, it could be openslide getting ready, or it could be the initial build of the pipeline, if it's very long. Source formats like tiff sometimes need converting before they can be processed, so you might be seeing a conversion delay. The `--vips-progress` flag is handy for seeing where vips is looping.

You can cache intermediate results, see vips_tilecache(). This can sometimes speed things up if you are getting a lot of recomputation. You can also write intermediates to memory images and reuse them. 

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-tilecache

**Comment by jcupitt** [comment] 2015-07-19 17:49
Hiya, I made a version of your gist here: https://gist.github.com/jcupitt/2a0e1ad5372d89c516df

I reformatted slightly, and added a main(). I added this to startup:

```python
    # turn on progress reporting
    Vips.progress_set(True)
```

This makes vips print out progress as it computes, so you can see where it's spending time. If I run it on a big openslide image I see:

```
$ ./roicutter.py ~/pics/openslide/50310.svs x.v
roicutter.py x.v: 18435 x 18435 pixels, 4 threads, 128 x 128 tiles, 256 lines in buffer
roicutter.py x.v: 9% complete
```

So it starts calculating immediately. Maybe you were running it on an image that vips had to preprocess?

**Comment by Jondeen** [comment] 2015-07-31 11:55
Hi again, 

Looking into your suggestions now -- how can I force a caching operation via the Python interface?

**Comment by jcupitt** [comment] 2015-07-31 12:24
I'm not sure there's anything to cache. It seems to run quickly (for me), even on huge images. 

If it's slow to start for you, it could be because of the file format you are using. What images are you running it on? Can you post some timings?

I see:

```
$ time ./roicutter.py /data/john/pics/openslide/54479.svs x.v
roicutter.py x.v: 12684 x 12684 pixels, 12 threads, 128 x 128 tiles, 384 lines in buffer
roicutter.py x.v: done in 8.1s          
real	0m14.522s
user	1m12.632s
sys	0m2.348s
```

**Comment by jcupitt** [comment] 2015-07-31 12:31
For caching, you can either write a complete image to memory and then process from that, or you can have a tile cache which keeps the most recent N tiles around for reuse. 

In Python, something like:

```python
mem = Vips.Image.new_memory()
image.write(mem)
image = mem
```

That will write `image` to a huge memory buffer called `mem`, then point `image` at he buffer of calculated pixels. It will chew up loads of memory, but it's very fast.

Alternatively, there's `tilecache`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-tilecache

Use it from Python like:

```python
image = image.tilecache(max_tiles = 100, threaded = True)
```

That'll keep the most recent 100 tiles and share them between image threads. It can help if you have lots of non-local references in your pipeline. If you are reusing values from the same place, vips should cache automatically and `tilecache` won't help.

**Comment by Jondeen** [comment] 2015-07-31 21:16
I see. Thank you for great examples -- as you guessed it made little impact on processing time, although I'll run some more tests later on larger datasets. I'm using JPEG compressed tiffs as input (suboptimal, alas space saving and wide compatibility).

**Comment by jcupitt** [comment] 2015-07-31 21:56
You should be able to use sequential mode, I think. It will eliminate the startup time. 

Try swapping the line:

```python
im = Vips.Image.new_from_file(sys.argv[1])
```

for:

```python
im = Vips.Image.new_from_file(sys.argv[1], access = Vips.Access.SEQUENTIAL)
```

**Comment by jcupitt** [comment] 2015-07-31 22:00
Alternatively, use tiled jpeg-compressed tiff. 

The problem is that vips like to be able to do random access to images, and vanilla tiff just does not support this. So vips has to decompress the whole image to a temporary random access disc file before it can start work, which I think is the long startup delay you were seeing. 

To fix this you can either use tiled tiff, which does support random access, or tell vips that your program will only read the image top-to-bottom and will not need random access.

I think your ROI program will work top-to-bottom, probably, so try that.

**Comment by Jondeen** [comment] 2015-08-01 11:23
Righto -- I've run some tests. First off -- the sequential access mode made little difference in the smaller images, I'll check with the larger but the problem seems to be lying elsewhere...

One image is approx the size of my ROI (but I add a ROI along border to make it comparable), and the other is maybe 4-6 times bigger with only a fraction of the image relevant to the analysis.

Using same thresholds etc the smaller image completes all steps of analysis at around 37 seconds whereas the larger one spends 100 seconds on each step.

This script does region cutting, colourspace conversion then thresholding (once on a negative reference, then on a positive) and finally saves the two images. These data were collected using the sequential access mode:

See log @ https://gist.github.com/Jondeen/38462f17ba6319b71ea1

**Comment by Jondeen** [comment] 2015-08-01 11:29
**Update:**
I ran the script on a different image with comparatively many pixels (2.8billion vs 3.3billion of the larger test image), and it ran at same speed as the small image. Only difference was that the dimensions were skewed in the vertical direction rather than horizontal:
```
X: min   9834px, max  37581px, size  27746px, orig size:  39092px
Y: min    231px, max  28055px, size  27823px, orig size:  73606px
...
Orders.py temp-1382: 27746 x 27823 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Orders.py temp-1382: done in 58.2s          
Orders.py temp-1387: 27746 x 27823 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Orders.py temp-1387: done in 56.1s
```

So it seems it's the line length that is causing issues rather than the size of the image itself..?

**Comment by jcupitt** [comment] 2015-08-02 08:15
Ah, sorry, I though you were just running the roi thing, I didn't realize you were doing other stuff too. 

Yes, it's looping four times over your image. Do you have enough RAM to keep a whole intermediate image around? If you do, run the first stage to memory, then process from that to your outputs. 

Can you post the complete script somewhere, or maybe mail it to me? I could have a look if you like.

**Comment by Jondeen** [comment] 2015-08-02 12:50
Thanks for day response as always!

I'll clean it up and put it on gist once I get home.

**Comment by Jondeen** [comment] 2015-08-02 15:08
Righto:
https://gist.github.com/Jondeen/19468c694d5bd2a50d86

This script fetches various data from a database to be used for thresholding and cutting.

**Comment by jcupitt** [comment] 2015-08-02 16:53
I can't easily run it, but looking through the script I noticed a couple of things:

* I would do the memory cache as late as possible, perhaps line 230, just after the `colourspace`
* make sure you are writing an 8-bit image to memory (perhaps you are?), a float will be HUGE
* each save operation will trigger a scan of the whole image, and each `.avg()` as well, I guess this is where your four passes over the image come from

**Comment by Jondeen** [comment] 2015-08-02 17:18
Hi again,

Yeah sorry about that I'll see if I can isolate the different functions a bit better so it's easier to run external tests on it...

The caching operation is forced after the image is trimmed based on min/max values https://gist.github.com/Jondeen/19468c694d5bd2a50d86#file-crunches-py-L119 before any other operation is called.

It does however incur a very small saving operation on my system ( ~ 10-20 secs see https://gist.github.com/Jondeen/898f7f7c7538fbf4f88a#file-log2-log-L7 ) and increases the overall computation on remaining steps...

I think it's 8 bit memory, since I haven't done any arithmetic operations on the image so guessing it should retain its original format? At the time of the caching I've only used im.crop(min[x],min[y],w,h).

As for the save/avg operations - will this scan the original image in full? Despite having forced a memory-save with only a sub-region of the image?

I'll isolate my data handling routines so they don't get in way of testing, I'll let you know once it is done.

**Comment by Jondeen** [comment] 2015-08-02 18:02
Hookay :)

https://gist.github.com/Jondeen/20213ca1d57b120b0c63

the thresholding function now accepts `vips_image_object,positive_data_object,reference_data_object,roi_data_object,caching_boolean`.

`vips_image_object` the data objects are dicts with necessary info in them as in the example dicts given at the top of the file (posDebug, refDebug and roiDebug). The coordinates are normalized to the width of the image.

**Comment by Jondeen** [comment] 2015-08-02 18:13
On second thought, another variable I didn't take into account was the number of coordinates used to define the ROI. It may have had a hidden impact on calculation times... It seems to matter quite significantly.

I'll continue to look into it, but as of now this seems to be the culprit of my laggy analysis...

**Comment by jcupitt** [comment] 2015-08-03 17:02
I hacked your program about slightly and made this:

https://gist.github.com/jcupitt/6a729e85f849959ce168

It runs without any DB stuff. With a 10k x 10k RGB image on my laptop I see:

```
$ time ../crunches2.py ~/pics/wtc.jpg 
threshold() ...
X: min    141px, max   2591px, size   2450px, orig size:   9372px
Y: min      0px, max   1977px, size   1977px, orig size:   9372px
crunches2.py temp-2: 2450 x 1977 pixels, 4 threads, 2450 x 16 tiles, 256 lines in buffer
crunches2.py temp-2: done in 0.134s          
Positive:
Colourspace: hsv
Channel 0:   0-213 Inverted: 1 Skipped: 0
Channel 1:  15-255 Inverted: 0 Skipped: 0
Channel 2:   0-233 Inverted: 0 Skipped: 0
Reference:
Colourspace: hsv
Channel 0:   0-255 Inverted: 0 Skipped: 1
Channel 1:  15-255 Inverted: 0 Skipped: 0
Channel 2:   0-233 Inverted: 0 Skipped: 0
averaging  ...
crunches2.py temp-3487: 2450 x 1977 pixels, 4 threads, 2450 x 16 tiles, 256 lines in buffer
crunches2.py temp-3487: done in 5.43s          
crunches2.py temp-3489: 2450 x 1977 pixels, 4 threads, 2450 x 16 tiles, 256 lines in buffer
crunches2.py temp-3489: done in 5.82s          
pos.avg() = 7.69045864173
ref.avg() = 142.58404509

real	0m12.119s
user	0m39.236s
sys	0m0.312s
```

You can see it loops three times: the first time it makes the memory copy of the input image, then the second two times, driven by the `.avg()`, it builds the ROI and calculates the mask average. It's calculating the ROI twice.

If I move the copy-to-memory to just before the `.colourspace()`:

https://gist.github.com/jcupitt/6537ccd3c2b0371fde9f

I see:

```
$ time ../crunches2.py ~/pics/wtc.jpg 
... [snip] ...
real	0m6.484s
user	0m20.420s
sys	0m0.196s
```

About twice as fast. Now it's rendering the ROI to the memory buffer once, then calculating the average from that.

**Comment by jcupitt** [comment] 2015-08-03 17:04
... and I agree, your ROI is rather complex. I'll look if there are any obvious speedup in that. 

One thing you could consider is adding circles as another primitive shape for building ROIs. They calculate very quickly, much faster than sets of straight lines.

**Comment by Jondeen** [comment] 2015-08-03 17:13
\* **face/desk** *
Of course. I inserted the caching routine at a point where it only affects the local object (inside the cut_image method).

I'll post results from my own system asap! Thanks so much again!

**Comment by Jondeen** [comment] 2015-08-03 17:19
First of thank you so much for pointing this out -- I'll run tests on my own end and post the results asap. 

Secondly, there is no need to look into ROI speedups per se -- unless it is for your own benefit :)

Like I said, I'll bring an update as soon as I get time.

**Comment by Jondeen** [comment] 2015-08-03 20:21
**Update.**

Without caching - 196 seconds:
```
Roi detected.
X: min   9462px, max  37919px, size  28456px, orig size:  39092px
Y: min    896px, max  26439px, size  25543px, orig size:  73606px
...
Crunches.py temp-890: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-890: done in 51.8s          
Crunches.py temp-937: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-937: done in 51.9s          
Crunches.py temp-967: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-967: done in 45.3s          
Crunches.py temp-969: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-969: done in 46.2s          
memory: high-water mark 816.86 MB
```

With caching - 95 seconds:
```
Roi detected.
X: min   9462px, max  37919px, size  28456px, orig size:  39092px
Y: min    896px, max  26439px, size  25543px, orig size:  73606px
Crunches.py temp-843: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-843: done in 49.2s          
...
Crunches.py temp-903: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-903: done in 16.9s          
Crunches.py temp-966: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-966: done in 24s          
Crunches.py temp-993: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-993: done in 2.47s          
Crunches.py temp-995: 28456 x 25543 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
Crunches.py temp-995: done in 2.43s
memory: high-water mark 2.75 GB
```

Thanks for helping me along!

**Comment by jcupitt** [comment] 2015-08-03 20:31
Much better! Nice! It's still looping 5+ times though. Are all of those necessary? I guess if it's only a few seconds it doesn't matter. 

If I were trying to speed it up more, I think I'd look in detail at the operations being executed for each ROI loop. There's probably a more efficient way of calculating the same thing.

**Comment by Jondeen** [comment] 2015-08-03 22:29
Hi,

As far as I can tell it loops twice for the control image writes to disk (once for reference/background image, once for test/foreground image). This seems natural.
The two last are when it calculates the means. 

Or are you saying it should only loop once regardless of the number of operations it performs?

Yes, the process could probably be sped up quite significantly, I was just looking for a easy implementation which required little overhead in intermediary images... Now that I've got a better feel for how computation is done in Vips I could look into finding a more suitable algorithm... once I find time  ;-)
Do you think the one you used in Nip2 could perform better?

**Comment by jcupitt** [comment] 2015-08-11 08:01
The nip2 one could possible be better, I don't know. You'd need to make a python version of it and benchmark. 

I'll close this issue -- open a new one for the next round.

**Closed by jcupitt** 2015-08-11 08:01 UTC
Labels: question
