### ISSUE TITLE
Automatic optimisation of region re-computation when combining two VipsImage

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#567] opened 2016-12-06 14:47 UTC
In most of the cases, it is possible to figure out and hard-code the optimal order of region computations to avoid re-computing the same pixels several times. 
However, there are cases in which the optimal sequence is not known a-priori.

One example I am facing in PhotoFlow are the Porter-Duff blending nodes, which have to combine two images with no a-priori knowledge of which one should be processed first.

Yesterday evening I ended up writing a small piece of code that solves the problem in a relatively simple way, and I thought it might be of interest for you as well…
The solution I adopted is to attach to each image a blob containing a vector of all their parent images, and to associate to each parent image the value of the TOTAL padding required at the current stage of the pipeline.
The vector of parent image is basically a flattened version of the pipeline dependency tree. If a parent image appears twice, it is inserted only once with the largest padding associated.

When combining two images, the code walks through the two arrays of parents and compares the padding associated to the common elements. The one with the largest padding on common parents is processed first.

The code is found here: https://github.com/aferrero2707/PhotoFlow/blob/stable/src/base/image_hierarchy.cc

Of course, the array of parents needs to be filled explicitly, at least for each operation that involves padding of input regions. Here is an example of how it is done: https://github.com/aferrero2707/PhotoFlow/blob/stable/src/operations/gaussblur.cc#L134

Finally, here is an example of comparison between two VipsImages, to determine which one should be processed first: https://github.com/aferrero2707/PhotoFlow/blob/stable/src/operations/blender.cc#L243

I think that this mechanism could be rather easily incorporated into VIPS itself, if you wish so…

**Comment by jcupitt** [comment] 2016-12-06 14:52
I wonder if you could get the same effect in a simpler way? How about
just having a bit of metadata on an image called `tile-padding`, or
something like that, which is supposed to be a hint about the amount
of extra edge processing that an image is likely to need.

This value would start off as zero for new images, but would slowly
grow when you used a non-local operator like `conv`. Conv might include
something like:

```python
out.tile_padding = in.tile_padding + mask.width / 2
```

From the point of view of the node graph, the `tile_padding` field would
equal the sum of all the tile margins below that subgraph.

We'd then have a new bit of API, something like:

```C
int vips_region_prepare_array(VipsRegion **regions, int n, VipsRect *rect);
```
which would call `vips_region_prepare()` on all the `n` regions, sorted by
`tile_padding`.

Do you think this might give most of the benefits of your approach?

**Comment by aferrero2707** [comment] 2016-12-06 14:56
What if image C depends on input images A and B, each with a different cumulative padding? Which one should one take? That’s exactly the complication I’ve been facing.

Here is a practical example:

Suppose you have two input images A and B, a strongly blurred version A’ of A (with a 100px padding) and a slightly blurred version B’ of B (with a 10px padding).

Now build an image C which is a linear combination of A’ and B: 

    C = xA’ + (1-x)B 

and then a final image D which is a linear combination of C and B’:

    D = xB’ + (1-x)C

The crucial point is: in which order should one evaluate B’ and C in the last linear combination? C has the larges cumulative padding, however in this specific case B’ should be evaluated first to avoid region re-computation…

This is why I had to keep track of the padding associated to each parent node… in the above example, the metadata in image C will tell that a 100px padding is applied to image A and 0px padding to image B, and the metadata in image B’ will tell that a 10px padding is applied to image B. 
The common graph node is only B, and therefore the region evaluation order should only be based on the padding of the B image, even if the padding of image A is larger…

**Comment by jcupitt** [comment] 2016-12-06 15:01
Hehe we are composing these intelligent and considered posts impressively quickly.

**Comment by aferrero2707** [comment] 2016-12-06 15:15
I went too fast, I need to cool down... ;-)

**Comment by jcupitt** [comment] 2016-12-06 15:47
Here's a tiny program that's a handy way to show the problem:

```python
#!/usr/bin/env python

import sys
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

Vips.leak_set(True)

kernel = Vips.Image.new_from_array([[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]])
im = Vips.Image.new_from_file(sys.argv[1], access = Vips.Access.SEQUENTIAL)
im = im.cast(Vips.BandFormat.FLOAT)

for i in range(1,int(sys.argv[3])):
    im = im - im.conv(kernel)

im.write_to_file(sys.argv[2])
```

Run with:

```
$ time ./resort.py /data/john/pics/k2.jpg x.jpg 10
memory: high-water mark 480.17 MB
real	0m2.970s
user	0m30.952s
sys	0m0.232s
```

Swap the inner loop for:

```
im = -im.conv(kernel) + im
```

And it gets much faster:

```
$ time ./resort.py /data/john/pics/k2.jpg x.jpg 10
memory: high-water mark 254.82 MB
real	0m0.843s
user	0m7.088s
sys	0m0.120s
```

Example taken from https://github.com/jcupitt/libvips/issues/556

**Comment by jcupitt** [comment] 2016-12-06 16:11
I had a quick hack. This branch:

https://github.com/jcupitt/libvips/tree/add-prepare-array

Implements my initial idea. There's a new thing to set padding, which `conv` sets, and a thing to prepare an array of regions in padding order, which `arithmetic` uses.

Trying that test program again, with `im = -im.conv(kernel) + im` I see:

```
$ time ./resort.py /data/john/pics/k2.jpg x.jpg 10
memory: high-water mark 254.82 MB
real	0m0.828s
user	0m7.160s
sys	0m0.112s
```

As before, but if I change the line back to `im = im - im.conv(kernel)` I see:

```
$ time ./resort.py /data/john/pics/k2.jpg x.jpg 10
memory: high-water mark 209.03 MB
real	0m0.722s
user	0m6.748s
sys	0m0.108s
```

It's a bit faster since it no longer needs the *-1. 

So it seems to help in this simple case, but I agree it's easy to imagine complex cases where it will make the wrong choice.

**Comment by jcupitt** [comment] 2016-12-06 17:44
I had a few more thoughts on this issue.

First, libvips has some internal API to walk the node graph: 

```
/* Apply a function to an image and all upstream or downstream images, 
 * direct and indirect. 
 */
void * 
vips__link_map( VipsImage *image, gboolean upstream,
        VipsSListMap2Fn fn, void *a, void *b )
```

This might be a better way to do the analysis for order optimization.

This is a relatively expensive thing to do, and we don't want to do it for every tile. This analysis should occur as the pipeline is built, not as it's evaluated. 

In complex cases we will see conflicting ordering constraints and it won't always be possible to find the best order by static analysis.

@aferrero2707 I don't suppose you could make a tiny python program that approximates the complex cases you are dealing with? It would be very handy to have a benchmark for this. I'll have a go if you've no time. 

I've done some more hacking on that branch. It now uses `vips_region_prepare_many()`everywhere it can, and sets padding in every area operation.

**Comment by aferrero2707** [comment] 2016-12-06 18:17
One advantage of my implementation is that the dependency tree is
automatically flattened into a linear array while it is filled. For
duplicated entries, the one with the largest padding is kept.

This way, the code that decides the optimal processing order does not need
to walk through the graph, instead it just runs two nested loops to compare
two linear arrays.
By the way, the decision-making code is of course executed when the
pipeline is built, not for each tile. It assumes that the optimal
processing order is the same for all tiles...

I am not really familiar with python, but I could try to make an example if
needed.

Il 06/dic/2016 18:44, "John Cupitt" <notifications@github.com> ha scritto:

**Comment by jcupitt** [comment] 2016-12-06 20:24
No problem, I'll have a go at a more complex case.

**Comment by aferrero2707** [comment] 2016-12-06 20:39
I think you can take the example in my previous post as a starting point: 

Suppose you have two input images A and B, a strongly blurred version A’ of A (with a 100px padding) and a slightly blurred version B’ of B (with a 10px padding).

Now build an image C which is a linear combination of A’ and B: 

    C = xA’ + (1-x)B 

and then a final image D which is a linear combination of C and B’:

    D = xB’ + (1-x)C

**Comment by jcupitt** [comment] 2017-01-07 17:14
Stuck on a train, so I had another look at this. Here's a test program:

```python
#!/usr/bin/python

import sys

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

if len(sys.argv) != 4:
    print "usage: %s in1 in2 out" % sys.argv[0]
    sys.exit(1)

Vips.leak_set(True)

a = Vips.Image.new_from_file(sys.argv[1])
b = Vips.Image.new_from_file(sys.argv[2])

# put an expensive operaton on these two so we can watch overcomputation
a = a.gaussblur(10)
b = b.gaussblur(10)

a_prime = a.gaussblur(10)
b_prime = b.gaussblur(1)

c = 0.1 * a_prime + 0.9 * b

d = 0.1 * b_prime + 0.9 * c
#d = 0.1 * c + 0.9 * b_prime

d.write_to_file(sys.argv[3])
```

Build libvips with `--enable-debug` and it prints overcomputation stats. If I run this test program under git master I see:

```
john@kiwi:~/try$ ./reorder.py ~/pics/k2.jpg ~/pics/k4.jpg x.v
vips_image_dispose: temp-146 vips_convi_gen_vector computed 101%
vips_image_dispose: temp-83 vips_convi_gen computed 103%
vips_image_dispose: temp-65 vips_convi_gen computed 129%
vips_image_dispose: temp-105 vips_convi_gen computed 124%
vips_image_dispose: temp-43 vips_convi_gen computed 157%
vips_image_dispose: temp-25 vips_convi_gen computed 188%
memory: high-water mark 53.72 MB
```

If I swap the `d` lines around, I see:

```
john@kiwi:~/try$ ./reorder.py ~/pics/k2.jpg ~/pics/k4.jpg x.v
vips_image_dispose: temp-146 vips_convi_gen_vector computed 101%
vips_image_dispose: temp-83 vips_convi_gen computed 203%
vips_image_dispose: temp-105 vips_convi_gen computed 124%
vips_image_dispose: temp-43 vips_convi_gen computed 157%
vips_image_dispose: temp-25 vips_convi_gen computed 188%
vips_image_dispose: temp-65 vips_convi_gen computed 255%
memory: high-water mark 54.49 MB
```

Significantly worse (as you'd expect).

If I run under the `add-prepare-array` branch that does naive region reordering, I see:

```
john@kiwi:~/try$ ./reorder.py ~/pics/k2.jpg ~/pics/k4.jpg x.v
vips_image_dispose: temp-136 vips_convi_gen_vector computed 101%
vips_image_dispose: temp-94 vips_convi_gen computed 124%
vips_image_dispose: temp-72 vips_convi_gen computed 203%
vips_image_dispose: temp-54 vips_convi_gen computed 255%
vips_image_dispose: temp-32 vips_convi_gen computed 157%
vips_image_dispose: temp-13 vips_convi_gen computed 188%
memory: high-water mark 54.49 MB
```

As bad as the bad order from git master. Again, reverse `d` and I see:

```
john@kiwi:~/try$ ./reorder.py ~/pics/k2.jpg ~/pics/k4.jpg x.v
vips_image_dispose: temp-94 vips_convi_gen computed 124%
vips_image_dispose: temp-32 vips_convi_gen computed 157%
vips_image_dispose: temp-13 vips_convi_gen computed 188%
vips_image_dispose: temp-136 vips_convi_gen_vector computed 101%
vips_image_dispose: temp-72 vips_convi_gen computed 203%
vips_image_dispose: temp-54 vips_convi_gen computed 255%
memory: high-water mark 54.49 MB
```

Equally bad. 

So my simple region reordering seems to be working, but (as you predicted) is making the wrong choice every time. At least it's working as intended and we can measure badness. 

I'll try implementing your fancy region reordering.

**Comment by aferrero2707** [comment] 2017-01-07 19:35
This is exactly the kind of non-trivial example I was thinking about... do not hesitate to ask me questions about my proposed region reordering code, as it is not very well written and really poorly commented.

Thanks for taking the time of putting together the example!

**Comment by jcupitt** [comment] 2017-01-12 14:46
Right, another attempt!

https://github.com/jcupitt/libvips/tree/prepare-reorder

This branch implements your fancy reordering algorithm, or a variant of it anyway. Things like conv now set a hint:

https://github.com/jcupitt/libvips/blob/prepare-reorder/libvips/convolution/conv.c#L116

And things like arithmetic use a new prepare function which does reordering:

https://github.com/jcupitt/libvips/blob/prepare-reorder/libvips/arithmetic/arithmetic.c#L519

The new code is here:

https://github.com/jcupitt/libvips/blob/prepare-reorder/libvips/iofuncs/reorder.c#L303

The "brains" are here:

https://github.com/jcupitt/libvips/blob/prepare-reorder/libvips/iofuncs/reorder.c#L160

That gets called whenever a new node is added to a pipeline. 

It seems to work, at least for that test Python program above. I always see the "fast" path being taken however I reorder the program, and turning on debugging and tracing though it all seems OK. 

What do you think?

**Comment by jcupitt** [comment] 2017-01-17 11:48
OK, merged to master. Thank you for this interesting feature!

**Closed by jcupitt** 2017-01-17 11:48 UTC
Labels: enhancement, in development
