### ISSUE TITLE
Best vips_sharpen() settings for general photography resizing?

### ISSUE THREAD

**Issue by davidb2002** [jcupitt/libvips#393] opened 2016-02-24 14:02 UTC
I'm currently using ImageMagick to resize and sharpen images. I'm now moving to VIPS due to performance reasons.

I use imageMagick's unsharpMask (http://php.net/manual/en/imagick.unsharpmaskimage.php) feature to sharpen a photo after resizing it. I'm currently using the following settings:
```
Radius: 0
Sigma: .5
Amount: .25
threshold: .008
```

vips_sharpen (http://www.vips.ecs.soton.ac.uk/supported/7.42/doc/html/libvips/libvips-convolution.html#vips-sharpen) has a number of additional parameters which i'm trying to replicate the same sharpening results.

Does anyone know an easy way to work out the VIPS translation of the imagemagick unsharp mask settings? There must be some sort of formula? Or what is a best 'general' sharpening settings for all round photography. It's to be used on a photography community of professional photographers. so I need a pretty good setup.

Thanks,
David

**Comment by jcupitt** [comment] 2016-02-24 14:58
Hi David, 

I'd use this doc link, you've got the 7.42 one there:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-convolution.html#vips-sharpen

Though sharpen hasn't changed.

The vips parameters are:

* `radius` is the same as `sigma` in IM. vips picks a radius for you based on the sigma setting.
* `x1` corresponds to `threshold`, though the scaling is different. The vips one is calculated on a L* difference image, I guess the IM one is in the range 0 - 1, so (probably?) multiply the IM value by 100.
* `y2` and `y3` don't seem to have an IM equivalent. They are useful in printing to limit the amount of haloing you get on edges, I don't know how useful they'd be for screen output. The defaults are probably reasonable, but you could try turning them down. 
* `m1` is (I think) always zero in IM, you could try making this a small value, it can make the transition from flat areas to edge areas less jarring.
* `m2` is equivalent to `amount`, I think, though the scaling is probably different. 

Have you tried nip2? It has this operator as a menu item, you can load a photo and drag sliders until you are happy with the result. You can zoom in on details too and check several points of interest at the same time, it's all live and fast (hopefully). You can calculate stats on the result too, if that's useful.

**Comment by davidb2002** [comment] 2016-02-24 15:09
Hi,

Thanks for the swift reply.

I've been testing and testing and the closes i've gotten was: r=1,x1=1.5,y2=2,y3=2,m1=0.4,m2=0.8

The biggest problem I have is the docs don't seem to give us any idea of what min/max values are for each (or defaults). 

I've not tried nip2, is there something I can run on Windows to tweak with sliders to get it just right it would be much quicker than tweaking and refreshing.

**Comment by jcupitt** [comment] 2016-02-24 16:12
Type `vips sharpen` at a command prompt to get min/max/default.

There's a Windows binary here:

http://www.vips.ecs.soton.ac.uk/supported/current/win32/

It's slightly clunky on Windows, you'll find the frame rate is best on Linux. You can install with `brew install nip2` on OS X, or `apt-get install nip2` or `yum install nip2` on Linux.

To try it out, drag an image into the main window (or File / Open) and click Toolkits / Filter / Convolution / Unsharp Mask. Doubleclick on the thumbnail to open a view window and zoom in on some feature you'd like to examine. You can have many view windows open, and they should all update as you drag sliders. 

Actually, now I try it it looks like the ranges have not been set correctly in libvips, I'll fix it.

**Comment by davidb2002** [comment] 2016-02-25 09:18
Hi,

Brilliant. This will massively quicken the comparison for what i'm trying to achieve. 

You mentioned the ranges haven't bin set correctly. Is this going to affect my results while I tweak the sliders? What are the acceptable ranges for each parameter of sharpen?

Cheers!

**Comment by jcupitt** [comment] 2016-02-25 10:57
`vips_sharpen()` was designed for print work really, rather than screen. In offset printing you need a pretty strong sharpen to hide the softness that you get from halftoning. It's hard to get the settings gentle enough for screen sharpening. 

I'm fiddling with the code now, I'll make the controls more sensitive.

**Comment by jcupitt** [comment] 2016-02-25 11:20
I've fixed up sharpen quite a bit:

https://github.com/jcupitt/libvips/commit/c1f1a7c1b373e030aa0fec8e55ab3562d42905c2

What platform are you running on and what API are you using?

**Comment by jcupitt** [comment] 2016-02-25 11:27
`vips_resize()` does a simple 3x3 convolution, you can see the code here:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/resize.c#L258

I'd use shrink-on-load + resize rather than trying to roll your own. You'll find shrink-on-load + affine will produce poor results for large resize factors. For example, a 5k x 5k JPEG -> 128x128 thumbnail will have horrible aliasing artifacts unless you do a block shrink.

`vips_resize()` does the following:

* block shrink (ie. an integer box filter) down to a size just above the target
* anti-alias blur
* affine to target
* 3x3 sharpen

It's equivalent (roughly) to lanczos2.

git master vips has a new block shrink and a new affine, you'll find `vips_resize()` is quite a bit quicker.

**Comment by KarlAustin** [comment] 2016-02-25 16:23
It was actually doing a shrink-on-load + shrink + affine :)

Tried master and yes, it's a lot quicker now using vips_resize() than it was when tested with a release.

**Comment by jcupitt** [comment] 2016-02-25 17:24
Did you build with -O3? That enables the auto-vectorizer, and the new `vips_resize()` has been redesigned to be vectorizable. You should see a nice improvement over -O2.

shrink-on-load + shrink + affine is OK, but you ought to find `vips_resize()` looks noticably better.

**Comment by kmartinez** [comment] 2016-02-26 09:03
Worth trying in nip2 (which is generally a fantastic spreadheet-like way to test your parameters)
I'm sure John can concoct a demo workspace for this - as it seems a pretty popular task. 

I'm always sceptical about sharpening after shrink - as an ideal shrink does not need it - its only clumsier shrinks that would tend to soften the result too much.

**Comment by jcupitt** [comment] 2016-02-26 12:06
`vips_resize()` needs a sharpen after shrink, since it has that anti-alias filter. The gauss blur before the affine makes a normalish shape, the sharpen after adds some negative lobes, so together you get a fast aproximation of a two-lobe sinc sampler, or lanczos2.

I agree that sharpen after a simple bicubic is rather dubious :( you could maybe argue you are compensating for problems in the display device, or your user's vision, or just their preferences.

**Comment by jcupitt** [comment] 2016-02-28 11:27
@davidb2002 git master vips now has a much nicer sharpen operator. The parameters can take a greater range of values, and there's a more sensitive control for the sigma. It's faster too.

**Comment by KarlAustin** [comment] 2016-02-29 13:02
Missed the bit about -O3 to start with.  Not seeing a difference though when passing:

C(XX)FLAGS="-g -O3"

Test VM, doing a resize from 2000px to 260px, save buffer as 95 quality jpeg, interlaced, optimised:

-O2
52.09
56.12
55.94

-O3
54.17
55.67
56.21

Numbers are requests per second (HTTP gateway to it).

**Comment by jcupitt** [comment] 2016-02-29 15:07
It depends which bit of the resizing pipeline are hit. The big speedup is for the block shrinker. For a 10k x 10k RGB I see:

```
CFLAGS="-O2" CXXFLAGS="-O2" ./configure --prefix=...
$ time vips shrink wtc.v x.v 10 10
real	0m0.211s
user	0m0.616s
sys	0m0.056s
CFLAGS="-O3" CXXFLAGS="-O3" ./configure --prefix=...
$ time vips shrink wtc.v x.v 10 10
real	0m0.139s
user	0m0.368s
sys	0m0.044s
```

**Comment by ScottKevill** [comment] 2016-03-11 06:45
Was going to open a new question issue, but this one is loosely related on the topic of thumbnail resizing and aliasing. I've only just started playing with VIPS (8.2.2) and am seeing pretty bad moiré patterns with vipsthumbnail compared with ImageMagick's convert -resize.

[Original source](http://kevill.com/test/test_800x600.jpg) image is 800x600 (which looks like it has already been resized).

75.0% = 600x450: [IM](http://kevill.com/test/test_600x450_im.jpg) vs [VIPS](http://kevill.com/test/test_600x450_vips.jpg)
50.0% = 400x300: [IM](http://kevill.com/test/test_400x300_im.jpg) vs [VIPS](http://kevill.com/test/test_400x300_vips.jpg)
37.5% = 300x225: [IM](http://kevill.com/test/test_300x225_im.jpg) vs [VIPS](http://kevill.com/test/test_300x225_vips.jpg)
25.0% = 200x150: [IM](http://kevill.com/test/test_200x150_im.jpg) vs [VIPS](http://kevill.com/test/test_200x150_vips.jpg)

Most noticeable is the roof, but also the aliasing in the power lines and the beams of the pergola at the left. The results improve as the thumbnails get smaller.

Any suggestions on how to improve the larger thumbnails? I've tinkered a bit using the C api instead of the vipsthumbnail command-line but haven't had any luck.

**Comment by jcupitt** [comment] 2016-03-11 08:55
Hi Scott, this sounds interesting, but can we move it to a new issue? 

libvips 8.3 will have a new downsizer and it would be nice to have an issue to discuss it in. I've made #404, I'll try your sample with the new code and post the results there.

**Comment by ScottKevill** [comment] 2016-03-11 09:20
No problem, wasn't sure if it was something simple I missed. :)

**Comment by jcupitt** [comment] 2016-03-14 10:16
The new downsizer is now in master and will be part of vips 8.3. Did the results look OK? Please reopen if not. There are some sample images on #404.

**Closed by jcupitt** 2016-03-14 10:16 UTC
Labels: enhancement, in development, question

**Comment by sergeevabc** [comment] 2024-01-26 01:54
It is a pity that by the end of this thread there is no answer as to which sharpen parameters are the best in a reduction case. Default seems too harsh sometimes.

**Comment by jcupitt** [comment] 2024-01-26 11:02
Hi @sergeevabc, please open a new discussion, I don't think this old issue is a good place to talk about current behaviour.
